name: Build & Release LiveCaptions-Translator (Windows Matrix)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [win-x64, win-arm64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - run: dotnet restore

      - name: Publish (${{ matrix.arch }})
        run: dotnet publish -c Release -r ${{ matrix.arch }} --self-contained false --no-restore

      - name: Find publish folder
        id: findpub
        shell: pwsh
        run: |
          $pub = Get-ChildItem -Recurse -Directory -Filter publish |
            Where-Object { $_.FullName -match "bin\\Release\\.*\\${{ matrix.arch }}\\publish$" } |
            Select-Object -First 1
          if (-not $pub) { throw "Publish folder not found." }
          echo "pubdir=$($pub.FullName)" >> $env:GITHUB_OUTPUT

      - name: Zip artifact
        run: Compress-Archive -Path "${{ steps.findpub.outputs.pubdir }}\\*" -DestinationPath "LiveCaptions-Translator-${{ matrix.arch }}.zip" -Force

      - uses: actions/upload-artifact@v4
        with:
          name: LiveCaptions-Translator-${{ matrix.arch }}
          path: LiveCaptions-Translator-${{ matrix.arch }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ github.run_number }}
          name: Nightly Build ${{ github.run_number }}
          body: |
            自动生成的最新 Windows 构建：
            - ✅ win-x64
            - ✅ win-arm64
          files: dist/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
